---
deployment:
  tasks:
    - export DEPLOYPATH=/home/manycez2q2t3/actiontrack
    - echo "--- Resetting repository to clean state ---"
    - cd $DEPLOYPATH && git reset --hard HEAD
    - cd $DEPLOYPATH && git clean -fd
    - echo "--- Running deployment tasks ---"
    - cd $DEPLOYPATH && /usr/local/bin/ea-php84 /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader 2>&1 || echo "Composer failed"
    - cd $DEPLOYPATH && /usr/local/bin/ea-php84 artisan migrate --force
    - cd $DEPLOYPATH && /usr/local/bin/ea-php84 artisan config:cache
    - cd $DEPLOYPATH && /usr/local/bin/ea-php84 artisan route:cache
    - cd $DEPLOYPATH && /usr/local/bin/ea-php84 artisan view:cache
    - echo "--- Deployment completed successfully ---"
